# Site settings
baseurl = "/"
languageCode = "en"
title = "flee"
theme = "hugo-theme-cactus-plus"
# googleAnalytics = "google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
    author = "laymonage"
    description = "free writing"
    avatarLink = ""
    avatarImage = "logo.svg"
    bio = "free writing about stuff<br>to flee from other stuff"

    # twitter = "twitter_id"
    # facebook = "facebook_id"

    enableRSS = true
    enableToc = true

    enableDisqus = true
    disqusShortname = "flee-laymonage"


    enableSummary = true
    # Set the value to true if use description in post front matter replace content summary
    useDescriptionReplaceSummary = false


    enableNetlifyCMS = true


    enableGoogleAnalytics = false
    enableBaiduAnalytics = false
    # Set the value to your baidu analysis code if you want to use baidu analytics
    # baiduAnalytics = 'baidu_analysis_code'

    enableTwitterCard = false
    # The url for twitter card image, default is avatar.png in static/images directory
    twitterCardImage = ""

    enableIconCompat = true

    # Add custom assets with their paths relative to the static folder
    customCSS = ["css/custom.css", "css/fonts.css"]
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = "home"
    about = "about"
    archive = "archive"
    subscribe = "subscribe"
    tags = "tags"

    olderPosts = ""
    newerPosts = ""
    copyright = ""

    # show latest posts in single page
    showLatestPosts = false
    readMore = ""

    # Share
    enableShare = false
    tweet = "tweet"
    share = "share"

    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
    # facebook-square = "https://fb.com/"
    # twitter-square = "https://twitter.com/"
    # github-square = "https://github.com/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
